### PR TITLE
#255 show support/flag/delete buttons in question list

### PR DESCRIPTION
**Pull request by danielhers**
Refactored the HTML for the buttons and their Javascript code to
separate files which are included from both question_details and
question_list.

Added template tags for QA, providing filters for can_vote and
can_delete, so that we don't need to pass them from the view (otherwise
we would need to pass them for each question in the question list). The
exception is can_answer, which is still passed because we don't want to
show it at all in the question list (we pass False). We want the
candidates to view the whole question before replying. (Also, it would
be too messy with the controls otherwise).

Since I didn't want to duplicate the JS for each control, I use the question-
id attribute of the question-summary div which is the closest parent of
the control. Since we can't pass that to the Django template url
function, I used a small hack where I passed a "numeric" constant which
will never be used to the url function, and then replaced it in the JS
with the correct question ID.

### CODE REVIEW

**Comment by tbrisker** [comment]
flagging does not work as expected on my local server - please check. (might be related to the auto mailing?)

**Comment by danielhers** [comment]
I also suspect it's because of send_mail. Does flagging work for you
without my change?

**Comment by daonb** [comment]
This is too ugly. mixing of text and icons just looks bad.  we need to change the text to icons: "Edit" to the pen icon and support to "+1".

**Comment by danielhers** [comment]
Good idea. Want to open a new issue?

**Comment by daonb** [comment]
IMO, we don't need a new ticket.  My guess is that fixing will take you no
more than 15 minutes, so you can go right ahead, fix it and reference this
ticket in the commit.

On 8 October 2013 11:22, Daniel Hershcovich notifications@github.comwrote:

> Good idea. Want to open a new issue?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/pull/348#issuecomment-25875505
> .

## 

http://yeda.us/daonb

**Comment by lotan1** [comment]
#352 ..

**Pull request merged**
