### PR TITLE
some changes to make installing a fresh copy easier

### PR DESCRIPTION
**Pull request by amirnissim**

### CODE REVIEW

**Comment by daonb** [comment]
Thanks!
I'll update the reademe file to include the installation of virtualenvwrapper - an easier to use wrapper around virtualenv. Regarding trunk8, we don't use it yet as it has a bug when truncating text with html so why worry about it?

**Comment by amirnissim** [comment]
RE trunk8 - I had a setting in my .gitattributes that fixes CRLF issues automatically.

Did active development move to the 'local' branch?
I hope to join you again soon (I heard rumors about a July hackathon?)

**Comment by daonb** [comment]
Glad you'll be joining me - I'm trying to keep the issues updated, so
please start there.

It's all on local for now.

There's a hackathon on the 19th-20 of july, this time in Tel Aviv and San
Francisco!

On 27 June 2013 21:34, Amir Nissim notifications@github.com wrote:

> RE trunk8 - I had a setting in my .gitattributes that fixes CRLF issues
> automatically.
> 
> Did active development move to the 'local' branch?
> I hope to join you again soon (I heard rumors about a July hackathon?)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/ok-qa/pull/70#issuecomment-20145605
> .

## 

http://yeda.us/daonb

**Comment by amirnissim** [comment]
Not relevant anymore.

**Pull request closed without merging**
