### PR TITLE
Edit profile fixes

### PR DESCRIPTION
**Pull request by danielhers**
Interface fixes for edit profile and reset password.

### CODE REVIEW

**Comment by tbrisker** [comment]
pull request has merge conflicts. please resolve - I'm guessing it has to do with the translation files.

**Comment by danielhers** [comment]
Please try again now.

**Comment by danielhers** [comment]
Right, conflicts with my own changes from other branches... How silly. I'll
fix it.

**Comment by tbrisker** [comment]
now breaks the ability to choose an initial locality on first login.

**Comment by tbrisker** [comment]
fixed and merged.

**Pull request merged**
