### PR TITLE
add url tags - view not implemented

### PR DESCRIPTION
**Pull request by iritmalka**

### CODE REVIEW

**Comment by daonb** [comment]
sorry, but the "Files Changes" on this pull request shows too many diffs. I believe it's because I work with 4 spaces indentation - expanding all tabs to 4 spaces, which is the standard python way. Please change the spacing and re-commit so It'll be easier to commit.

Benny

**Comment by iritmalka** [comment]
oh right, i'll fix it tonight

**Comment by daonb** [comment]
I'll do it myself in an hour

**Comment by iritmalka** [comment]
i forgot about it, sorry

**Comment by yaninelbi** [comment]
no cookies for you today!

**Comment by daonb** [comment]
Well, you still got a chance... I got caught up in the search and we'll
probably get back to it on saturday evening.

**Comment by iritmalka** [comment]
I'll do it tonight

**Pull request merged**
